#!/bin/bash

if [[ -z $1 && -z $2 ]]
then
        echo "ERROR! You must write the directory and the commit message!"
	echo "Example:"
	echo "commit . \"Updating some file\""
else
	echo "Commiting your changes..."
        cd $1
	if [[ -z $3 ]]
	then
        	git commit -a -m "$2" && git push	
	else
        	git commit -a -m "$2"
	fi
	echo "Done commiting"
fi
