#!/bin/bash

if [[ -z $1 && -z $2 ]]
then
        echo "ERROR! You must write the directory and the commit message!"
	echo "Example:"
	echo "commit . \"Updating some file\""
else
	printf "Commiting your changes...\n\n"
        cd $1
	if [[ ! -z $3 && $3 = "push" ]]
	then
        	git commit -a -m "$2"
		printf "\n\nPushing your changes to server...\n\n"
		git push
		printf "\n\nPushing your changes to server...\n\n"
	else
        	git commit -a -m "$2"
	fi
	printf "\n\nDone"
fi
